In [ ]:
import numpy as np
data_list = [10, 20, 30, 40, 50]
arr = np.array(data_list)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


In [ ]:
zeros_matrix = np.zeros((3, 4))
ones_matrix = np.ones((2, 5))

print("Zeros Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)
print("\nOnes Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [ ]:

original = np.arange(1, 13)
reshaped = original.reshape(3, 4)

print("Original Array:", original)
print("Original Shape:", original.shape)
print("\nReshaped Matrix:\n", reshaped)
print("Reshaped Shape:", reshaped.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [ ]:
rand_arr = np.random.randint(1, 100, 10)

print("Array:", rand_arr)
print("Min:", rand_arr.min())
print("Max:", rand_arr.max())
print("Mean:", rand_arr.mean())
print("Sum:", rand_arr.sum())

Array: [72 44 47 36 63 51 62 27 36 68]
Min: 27
Max: 72
Mean: 50.6
Sum: 506


In [ ]:
import pandas as pd

# Pandas DataFrame
data = {'Student Name': ['Mahir', 'Aryan', 'Charlie'], 'Marks': [89, 90, 78]}
df = pd.DataFrame(data)

print("DataFrame:\n", df)
print("\nData Types:\n", df.dtypes)

DataFrame:
   Student Name  Marks
0        Mahir     89
1        Aryan     90
2      Charlie     78

Data Types:
 Student Name    object
Marks            int64
dtype: object


In [ ]:
import pandas as pd

# Reading CSV
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
print("First 5:\n", df.head())
print("Last 5:\n", df.tail())

First 5:
    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
Last 5:
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0

In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_train.csv')
summary = df.describe()

print("--- Statistical Summary of the Dataset ---")
print(summary)
target_col = df.select_dtypes(include=['number']).columns[0]

print(f"\n--- Interpretation for Column: {target_col} ---")
print(f"Mean (Average): {summary.loc['mean', target_col]:.2f}")
print(f"Standard Deviation (Spread): {summary.loc['std', target_col]:.2f}")
print(f"Minimum Value: {summary.loc['min', target_col]}")
print(f"Maximum Value: {summary.loc['max', target_col]}")

--- Statistical Summary of the Dataset ---
          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.00